ALTER TABLE tb_clinica ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_tutor ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_pet ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_veterinario ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
